export const GET_CONTACTS_LOAD ="GET_CONTACTS_LOAD"
export const GET_CONTACTS_SUCC ="GET_CONTACTS_SUCC"
export const GET_CONTACTS_FAIL ="GET_CONTACTS_FAIL"

export const DELETE_CONTACT_SUCCES ="DELETE_CONTACT_SUCCES"
export const DELETE_CONTACT_FAIL ="DELETE_CONTACT_SUCCES"

export const ADD_CONTACT_SUCCES="ADD_CONTACT_SUCCES"
export const ADD_CONTACT_FAIL="ADD_CONTACT_FAIL"

export const TOGGLE_TRUE="TOGGLE_TRUE"
export const TOGGLE_FALSE="TOGGLE_FALSE"

export const GET_CONTACT_LOAD ="GET_CONTACT_LOAD"
export const GET_CONTACT_SUCC ="GET_CONTACT_SUCC"
export const GET_CONTACT_FAIL ="GET_CONTACT_FAIL"

export const EDIT_CONTACT_SUCCES="EDIT_CONTACT_SUCCES"
export const EDIT_CONTACT_FAIL="EDIT_CONTACT_FAIL"
